runtime: python39

entrypoint: waitress-serve --port=$PORT server:app

handlers:
  - url: /static
    static_dir: static
  - url: /templates
    static_dir: templates

  - url: /.*
    script: auto

env_variables:
  API_KEY: "ca49d5d57702bddcbc9093265138e8fa"
